name: Build and Push to GHCR
on:
  workflow_call:
  push:
    tags:
      - "v*"

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: "1.24"

      - name: Create bundle
        run: make create-bundle

      - name: Setup ORAS
        uses: oras-project/setup-oras@v1.2.4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare image tags
        id: prepare-tags
        run: |
          RELEASE_VERSION=${GITHUB_REF/refs\/tags\/v/}
          MINOR_VERSION=$(echo $RELEASE_VERSION | cut -d. -f1,2)
          MAJOR_VERSION=$(echo $RELEASE_VERSION | cut -d. -f1)
          tags=("latest" "$RELEASE_VERSION" "$MINOR_VERSION" "$MAJOR_VERSION")
          echo "tags=${tags[*]}" >> $GITHUB_OUTPUT

      - name: Deploy checks bundle to GHCR
        run: |
          tags=(${{ steps.prepare-tags.outputs.tags }})
          registry="ghcr.io/${{ github.repository }}"
          for tag in ${tags[@]}; do
            echo "Pushing artifact to ${registry}:${tag}"
            if oras push ${registry}:${tag} \
              --artifact-type application/vnd.cncf.openpolicyagent.config.v1+json \
              bundle.tar.gz:application/vnd.cncf.openpolicyagent.layer.v1.tar+gzip; then
              echo "Successfully pushed artifact to ${registry}:${tag}"
            else
              echo "Failed to push artifact to ${registry}:${tag}"
              exit 1
            fi
          done